spring:
  application:
    name: config-server-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /apps/config
server:
  port: ${CONFIG_SERVER_PORT:8888}