server:
  port: ${EUREKA_SERVER_PORT:8761}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureca-discovery-service:${EUREKA_SERVER_PORT:server.port}/eureka/