server:
  port: ${PORT:8100}

spring:
  webflux:
    base-path: /api/v1

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - refresh
          - beans

doc:
  info:
    title: "Favorite product REST APIs"
    description: ""
    version: "1.0"
    terms-of-service-url: ""
    license: ""
    licence-url: ""
  contact:
    name: "Zaytsev Andrey"
    url: "https://github.com/Zaytsev-Andrey/"
    email: "zaytsev.andrey.al@yandex.ru"
  api-key:
    name: "Authorization"
    keyname: "Authorization"
    pass-as: "header"
  authorization-scope:
    scope: "global"
    description: "accessEverything"