server:
  port: ${PORT:8080}

spring:
  webflux:
    base-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - refresh
          - beans