eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/

logging:
  level:
    root: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm
          jwk-set-uri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            clientId: search-product-service
            clientSecret: ${CLIENT_SECRET}
            authorizationGrantType: client_credentials
        provider:
          keycloak:
            authorizationUri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm/protocol/openid-connect/auth
            tokenUri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm/protocol/openid-connect/token
            userInfoUri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm/protocol/openid-connect/userinfo
            jwkSetUri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm/protocol/openid-connect/certs
            introspectionUri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm/protocol/openid-connect/token/introspect