server:
  port: ${PORT:8080}

spring:
  webflux:
    base-path: /api/v1

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8060/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - refresh
          - beans