default-client-registration: keycloak

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm
          jwk-set-uri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            clientId: telegram-bot-service
            clientSecret: ${CLIENT_SECRET}
            authorizationGrantType: client_credentials
        provider:
          keycloak:
            authorizationUri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm/protocol/openid-connect/auth
            tokenUri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm/protocol/openid-connect/token
            userInfoUri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm/protocol/openid-connect/userinfo
            jwkSetUri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm/protocol/openid-connect/certs
            introspectionUri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8080}/auth/realms/space-price-realm/protocol/openid-connect/token/introspect

bot:
  authorization:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}