server:
  port: ${PORT:8090}

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - refresh
          - beans

bot:
  connection:
    search-product-service:
      host: http://localhost:8050/        # must end to /
      service: search-product-service
      base-path: /api/v1
      path: /product
      param-name: searchName
    favorite-product-service:
      host: http://localhost:8050/        # must end to /
      service: favorite-product-service
      base-path: /api/v1
      path: /favorite

  card-slider:
    capacity: 5     # must be greater than zero
    load-limit: 1   # must be greater than zero and less than or equals to capacity